version: "3"
services:
  app-rop-core-server:
    container_name: "rop-core-server"
    build: .
    network_mode: "host"
    restart: always
    environment:
      - ROP_HOSTNAME=localhost
      - RTSP_PLAY_URL_PREFIX=rtsp://localhost:61008
      - ROP_ALARM_WEBHOOK=
    working_dir: /app
    volumes:
      - "./data/:/data/"
      - "./app/:/app/"
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
        max-file: "3"
    command:
      [ "bash", "/data/start.sh" ]

    