"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ECommand = void 0;
var ECommand;
(function (ECommand) {
    ECommand[ECommand["NET_HEART_BEAT_V30"] = 0] = "NET_HEART_BEAT_V30";
    ECommand[ECommand["NET_APP_HAND_SHAKE_V30"] = 458] = "NET_APP_HAND_SHAKE_V30";
    ECommand[ECommand["NET_PREVIEW_V30"] = 3] = "NET_PREVIEW_V30";
    ECommand[ECommand["NET_PREVIEW_STOP_V30"] = 4] = "NET_PREVIEW_STOP_V30";
    ECommand[ECommand["NET_REPLAY_V30"] = 5] = "NET_REPLAY_V30";
    ECommand[ECommand["NET_REPLAY_STOP_V30"] = 7] = "NET_REPLAY_STOP_V30";
    ECommand[ECommand["NET_FILE_INFO_V30"] = 13] = "NET_FILE_INFO_V30";
    ECommand[ECommand["NET_PTZ_CONTROL_V30"] = 18] = "NET_PTZ_CONTROL_V30";
    ECommand[ECommand["NET_ALARM_V30"] = 33] = "NET_ALARM_V30";
    ECommand[ECommand["NET_UPDATE_DEV_V30"] = 67] = "NET_UPDATE_DEV_V30";
    ECommand[ECommand["NET_SNAP_V30"] = 109] = "NET_SNAP_V30";
    ECommand[ECommand["NET_GET_WIFI_INFO_V30"] = 116] = "NET_GET_WIFI_INFO_V30";
    ECommand[ECommand["NET_SET_WIFI_INFO_V30"] = 117] = "NET_SET_WIFI_INFO_V30";
    ECommand[ECommand["NET_REPLAY_SEEK_V30"] = 123] = "NET_REPLAY_SEEK_V30";
    ECommand[ECommand["NET_GET_REPLAY_CALENDAR_V30"] = 142] = "NET_GET_REPLAY_CALENDAR_V30";
    ECommand[ECommand["NET_GET_SYSGENERAL_CFG_V30"] = 104] = "NET_GET_SYSGENERAL_CFG_V30";
    ECommand[ECommand["NET_SET_SYSGENERAL_CFG_V30"] = 105] = "NET_SET_SYSGENERAL_CFG_V30";
    ECommand[ECommand["NET_REQUEST_IFRAME_V30"] = 189] = "NET_REQUEST_IFRAME_V30";
    ECommand[ECommand["NET_SUPPORT_V30"] = 199] = "NET_SUPPORT_V30";
    ECommand[ECommand["NET_WIFI_TEST_V30"] = 200] = "NET_WIFI_TEST_V30";
    ECommand[ECommand["NET_GET_RF_CFG_V30"] = 212] = "NET_GET_RF_CFG_V30";
    ECommand[ECommand["NET_SET_RF_CFG_V30"] = 213] = "NET_SET_RF_CFG_V30";
    ECommand[ECommand["NET_SET_DEVICE_SLEEP"] = 233] = "NET_SET_DEVICE_SLEEP";
    ECommand[ECommand["NET_FILE_FIND_V30"] = 459] = "NET_FILE_FIND_V30";
    ECommand[ECommand["NET_WAKE_UP_V30"] = 460] = "NET_WAKE_UP_V30";
    ECommand[ECommand["NET_GET_ALARM_REPORT_SWITCH_STATE_V30"] = 461] = "NET_GET_ALARM_REPORT_SWITCH_STATE_V30";
    ECommand[ECommand["NET_SET_ALARM_REPORT_SWITCH_STATE_V30"] = 462] = "NET_SET_ALARM_REPORT_SWITCH_STATE_V30";
    ECommand[ECommand["NET_REPORT_NETINFO_V30"] = 464] = "NET_REPORT_NETINFO_V30";
})(ECommand = exports.ECommand || (exports.ECommand = {}));
//# sourceMappingURL=Command.js.map